/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "CustomGUI"

pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://repo.papermc.io/repository/maven-public/")
    }
}